### ISSUE TITLE
[Bug]: Imprecise error message when confirming new password

### ISSUE THREAD

**Issue by rbento1096** [iter-idea/IDEA-Ionic6-extra#61]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature

After a user is invited to join an app (e.g. AIRP) and logging in with AWS' generated password, he is asked to submit a new password. If the password is invalid he should receive precise messages detailing the error (e.g. not enough characters, or 'missing an upper-case letter')

### Anomaly

When signing up for AIPR from an invite link, typing a password with no uppercase letters or symbols will produce the error message 'Password must contain at least 8 characters' event when the password has 8 or more characters

### Cause

Likely there is no control on what causes the password to be invalid, defaulting to the password length error message

### Correction (suggestion)

If the password is too short, throw the current error, otherwise control what is causing the submission to fail and produce an error message accordingly

### Example

Invite an user to join the an organization on AIRP.
Login with the provided credentials
On the confirm new password screen, enter a password with 8+ characters and no upper case letters or symbols.
You should get an error stating the password is too short
Add an uppercase letter and a symbol to the password and try again
You should be able to login now.

### What device are you seeing the problem on?

Desktop (MacOS)

### What browsers are you seeing the problem on?

Chrome

**Comment by uatisdeproblem** [comment]
Solved by https://github.com/iter-idea/IDEA-Ionic6-extra/releases/tag/v6.13.0
